/**
 * This file was auto-generated by scripts/generate-api-paths.mjs.
 * Do not make direct changes to the file.
 */

import type { paths } from './api';

/**
 * Every path template the API publishes. The proxy route compiles these into
 * matchers and refuses anything they do not cover, so this is the list that
 * decides what a browser can reach through this application's server.
 */
export const API_PATH_TEMPLATES = [
  '/api/metrics',
  '/api/v1/activity-feed',
  '/api/v1/activity-feed/{id}/retry',
  '/api/v1/admin/feature-flags',
  '/api/v1/admin/feature-flags/{id}',
  '/api/v1/admin/ui-config',
  '/api/v1/admin/users',
  '/api/v1/admin/users/{id}',
  '/api/v1/auth/forgot-password',
  '/api/v1/auth/get-user-by-email',
  '/api/v1/auth/guest-session',
  '/api/v1/auth/login',
  '/api/v1/auth/logout',
  '/api/v1/auth/magic-link',
  '/api/v1/auth/magic-link/verify',
  '/api/v1/auth/refresh-token',
  '/api/v1/auth/register',
  '/api/v1/auth/sso/facebook/data-deletion',
  '/api/v1/auth/sso/facebook/data-deletion/status/{confirmationCode}',
  '/api/v1/auth/sso/{provider}/register',
  '/api/v1/carrier-lookup',
  '/api/v1/consent-links/{token}',
  '/api/v1/consent-links/{token}/decline',
  '/api/v1/consent-links/{token}/grant',
  '/api/v1/features',
  '/api/v1/healthcheck',
  '/api/v1/klaviyo/checkout-started',
  '/api/v1/klaviyo/order-confirmed',
  '/api/v1/location-requests',
  '/api/v1/location-requests/sms-count',
  '/api/v1/location-requests/{id}',
  '/api/v1/location-requests/{id}/send-sms',
  '/api/v1/notification/center',
  '/api/v1/notification/center/read',
  '/api/v1/notification/center/unread/count',
  '/api/v1/reverse-lookup-reports',
  '/api/v1/reverse-lookup-reports/usage-count',
  '/api/v1/reverse-lookup-reports/{id}',
  '/api/v1/reverse-lookup-reports/{reportId}/data-breach',
  '/api/v1/reverse-lookup-reports/{reportId}/owners/{ownerId}/sex-offender',
  '/api/v1/reverse-lookup-reports/{reportId}/pdf',
  '/api/v1/reverse-lookup-reports/{reportId}/pdf/status',
  '/api/v1/reverse-lookup-reports/{reportId}/sections',
  '/api/v1/reverse-lookup-upsellings/consume',
  '/api/v1/reverse-lookup-upsellings/credits',
  '/api/v1/support/contact-us',
  '/api/v1/user',
  '/api/v1/user/me',
  '/api/v1/user/me/delete',
  '/api/v1/user/me/language',
  '/api/v1/user/me/password',
] as const satisfies readonly (keyof paths)[];
