apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mobitrace-frontend.fullname" . }}
spec:
  target:
    name: {{ include "mobitrace-frontend.fullname" . }}
    deletionPolicy: Delete
    template:
      type: Opaque
  secretStoreRef:
    name: cluster-external-store
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: /manual/{{ .Values.environment }}/{{ include "mobitrace-frontend.fullname" . }}
